# -*- coding: utf-8 -*-
"""Chess Heatmap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SjlGzFWLmnlnDJShMspZH2glQQ0Pc8zb
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import random

class piece:
  def __init__(self, x, y):
    self.y = y
    self.x = x
  def move(self,a,b):
    self.x+=a
    self.y+=b
    return self
  def randommove(self):
    a,b=random.choice([(1,3),(3,1),(-3,-1),(-1,-3),(-1,3),(1,-3),(-3,1),(3,-1)])
    self.x+=a
    self.y+=b
    return self
  def getxy(self):
    return (self.x,self.y)

xs=[]
ys=[]
a=piece(0,0)
for i in range(1000000):
  a.randommove()
  xs.append(a.getxy()[0])
  ys.append(a.getxy()[1])

heatmap, xedges, yedges = np.histogram2d(xs, ys)
extent = [xedges[0], xedges[-1], yedges[0], yedges[-1]]
plt.clf()
plt.imshow(heatmap,extent=extent,origin='Lower')
plt.axes().set_aspect('equal', 'datalim')
plt.colorbar()
plt.show()